name: PHP Checks

on: [ push ]

jobs:
  php-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0' ]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PHP CodeSniffer Check
        run: |
          composer install --prefer-dist --no-progress
          composer require staabm/annotate-pull-request-from-checkstyle
          ./vendor/bin/phpcs -q --report=checkstyle | vendor/bin/cs2pr --graceful-warnings
